### ISSUE TITLE
Use PipeWriter to write asynchronously

### ISSUE THREAD

**Issue by simrankedia** [sagebind/sluice#17]
Hi,

I want to use PiperWriter to write to sluice channel in chunks, I receive a chunk of byte array in fixed intervals in a callback function which I want to write to PipeWriter so the reader on the other end can read it. 

The documentation is not clear on the usage examples. Please let me know how to write using PipeWriter?

**Comment by sagebind** [comment]
Thanks for the question! `PipeWriter` implements [`AsyncWrite`](https://docs.rs/futures/0.3.14/futures/io/trait.AsyncWrite.html), so you can write to it asynchronously like any other asynchronous writer. Usually you would use something like [`AsyncWriteExt`](https://docs.rs/futures/0.3.14/futures/io/trait.AsyncWriteExt.html) to make writing more ergonomic. Something like this:

```rust
use futures::io::{AsyncRead, AsyncReadExt, AsyncWrite, AsyncWriteExt};

let mut (reader, writer) = sluice::pipe::pipe();

// Write to the writer.
writer.write(b"hello world").await?;

// Read it back from the reader.
let mut buf = [0; 11];
reader.read(&mut buf).await?;

assert_eq!(&buf, b"hello world");
```
