### ISSUE TITLE
Use async-channel or flume

### ISSUE THREAD

**Issue by nullchinchilla** [sagebind/sluice#18]
`futures-channel` is known to be of poor performance; would using `async-channel` or `flume` be considered?

**Comment by sagebind** [comment]
Certainly! Sluice was initially written before either async-channel or flume were created, but those are both better options than futures-channel today. I usually prefer async-channel since flume has a heavier dependency tree.

**Comment by sagebind** [comment]
Thanks for the suggestion! Sluice now uses async-channel under the hood in [version 0.5.5](https://github.com/sagebind/sluice/releases/tag/0.5.5)!
